import { BeachBoysChord, SongPreset } from '../types';
import { BEACH_BOYS_PRESETS } from './harmonyEngine';
import { BOB_DYLAN_WEIRDO_PRESETS } from './dylanStructureEngine';

export interface ExtendedSongPreset extends SongPreset {
  artistDna:
    | 'beach_boys'
    | 'bob_dylan'
    | 'radiohead'
    | 'big_thief'
    | 'dangelo'
    | 'microphones'
    | 'neutral_milk_hotel'
    | 'godspeed';
  tuningName: string;
  grooveVibe: string;
}

export const ALL_SONGWRITER_PRESETS: ExtendedSongPreset[] = [
  // 1. Beach Boys
  {
    ...BEACH_BOYS_PRESETS[0], // God Only Knows
    artistDna: 'beach_boys',
    tuningName: 'Standard (E A D G B E)',
    grooveVibe: 'Floating inverted bass, Scully 8-track tape chamber, close barbershop',
  },
  {
    ...BEACH_BOYS_PRESETS[1], // Wouldn't It Be Nice
    artistDna: 'beach_boys',
    tuningName: 'Standard (E A D G B E)',
    grooveVibe: 'Rapid doo-wop vocal punch, optimistic modulations, Wrecking Crew rhythm',
  },
  {
    ...BEACH_BOYS_PRESETS[2], // Surfer Girl
    artistDna: 'beach_boys',
    tuningName: 'Standard (E A D G B E)',
    grooveVibe: '6/8 slow dance, Four Freshmen stacked major 6ths, pure falsetto vibrato',
  },

  // 2. Bob Dylan ("Structure Weirdo")
  {
    id: 'dylan_tangled',
    title: 'Tangled Up in Blue (13-Bar Asymmetric Verse)',
    album: 'Blood on the Tracks',
    year: 1975,
    key: 'A Major (Open D Capo 2)',
    tempo: 98,
    harmonyStyle: 'pet_sounds',
    description: '⚡ BOB DYLAN WEIRDO: Asymmetric 13-bar verse structure featuring a sudden 2/4 lyrical breath cut at bar 9 and a 6/4 held harmonica turnaround at bar 13.',
    funFact: 'Dylan wrote this after studying painting with Norman Raeben, trying to tell a story where time is non-linear and verses stretch whenever the lyric overflows.',
    artistDna: 'bob_dylan',
    tuningName: 'Open D (D A D F# A D) Capo 2',
    grooveVibe: 'Irregular meter, 2/4 lyrical breath pause, 6/4 harmonica vamp, urgent folk rake',
    chords: BOB_DYLAN_WEIRDO_PRESETS[0].chords,
  },
  {
    id: 'dylan_desolation',
    title: 'Desolation Row (11-Bar Epic Ballad)',
    album: 'Highway 61 Revisited',
    year: 1965,
    key: 'E Major',
    tempo: 104,
    harmonyStyle: 'pet_sounds',
    description: '⚡ BOB DYLAN WEIRDO: 11-bar phrase cycles with a 3/4 hiccup at bar 7 and 5/4 harmonica cadence. Charlie McCoy nylon-string flourishes.',
    funFact: 'Recorded past midnight in Columbia Studio A in New York with legendary Nashville session guitarist Charlie McCoy.',
    artistDna: 'bob_dylan',
    tuningName: 'Standard (E A D G B E)',
    grooveVibe: 'Hypnotic 11-measure folk cycles, 3/4 and 5/4 lyrical expansions, steady acoustic thumb',
    chords: BOB_DYLAN_WEIRDO_PRESETS[1].chords,
  },
  {
    id: 'dylan_johanna',
    title: 'Visions of Johanna (Rubato Mercury Sound)',
    album: 'Blonde on Blonde',
    year: 1966,
    key: 'A Major',
    tempo: 96,
    harmonyStyle: 'pet_sounds',
    description: '⚡ BOB DYLAN WEIRDO: Elastic verse phrasing with 6/4 suspended breath holds and 2/4 cuts under Dylan\'s famous Blonde on Blonde "thin wild mercury sound".',
    funFact: 'Dylan described the sound he was pursuing on Blonde on Blonde as "that thin, that wild mercury sound. It\'s metallic and bright gold, with whatever that conjures up."',
    artistDna: 'bob_dylan',
    tuningName: 'Standard (E A D G B E)',
    grooveVibe: 'Rubato acoustic strums, 6/4 organ holds, 2/4 dynamic snaps, fragile poetry',
    chords: BOB_DYLAN_WEIRDO_PRESETS[2].chords,
  },

  // 3. Radiohead
  {
    id: 'radiohead_pyramid',
    title: 'Pyramid Song (16-Beat Swing Polymeter)',
    album: 'Amnesiac',
    year: 2001,
    key: 'F# Minor',
    tempo: 80,
    harmonyStyle: 'smile_poly',
    description: 'Syncopated 16-beat cycle grouped as 3 + 3 + 4 + 3 + 3. Features brooding modal interchange, Lydian #11 harmonies, and Charles Mingus jazz swing push.',
    funFact: 'Thom Yorke wrote this piano progression in a single afternoon after visiting an exhibition of ancient Egyptian underworld art in Copenhagen.',
    artistDna: 'radiohead',
    tuningName: 'Standard (E A D G B E)',
    grooveVibe: 'Polyrhythmic piano syncopation (3+3+4+3+3), Lydian #11 tensions, ghost snare swing',
    chords: [
      {
        id: 'rh_1',
        name: 'F#m',
        numeral: 'i',
        root: 'F#',
        quality: 'Minor',
        inversion: 'Root',
        durationBeats: 3,
        lyricsSnippet: 'I jumped in the river and what did I see?...',
        vowel: 'ooh',
        notes: { falsetto: 73, tenor1: 69, lead: 66, baritone: 61, bass: 42 },
        voicingDescription: 'Haunting dark open minor voicing',
      },
      {
        id: 'rh_2',
        name: 'Gmaj7#11',
        numeral: 'bIImaj7#11',
        root: 'G',
        quality: 'Major #11',
        inversion: 'Root',
        durationBeats: 3,
        lyricsSnippet: 'Black-eyed angels swam with me...',
        vowel: 'aah',
        notes: { falsetto: 74, tenor1: 71, lead: 66, baritone: 62, bass: 43 },
        voicingDescription: 'Phrygian/Lydian modal interchange chord with C# #11 chime',
      },
      {
        id: 'rh_3',
        name: 'F#m',
        numeral: 'i',
        root: 'F#',
        quality: 'Minor',
        inversion: 'Root',
        durationBeats: 4,
        lyricsSnippet: 'A moon full of stars and reason to doubt...',
        vowel: 'ooh',
        notes: { falsetto: 73, tenor1: 69, lead: 66, baritone: 61, bass: 42 },
        voicingDescription: 'Return to resting tonic',
      },
      {
        id: 'rh_4',
        name: 'A6',
        numeral: 'bIII6',
        root: 'A',
        quality: 'Major 6th',
        inversion: 'Root',
        durationBeats: 3,
        lyricsSnippet: 'All my lovers were there with me...',
        vowel: 'aah',
        notes: { falsetto: 73, tenor1: 69, lead: 64, baritone: 61, bass: 45 },
        voicingDescription: 'Melancholy major 6th lift',
      },
      {
        id: 'rh_5',
        name: 'G#dim7',
        numeral: 'vii°7',
        root: 'G#',
        quality: 'Diminished 7th',
        inversion: 'Root',
        durationBeats: 3,
        lyricsSnippet: 'All my past and futures...',
        vowel: 'ooh',
        notes: { falsetto: 74, tenor1: 71, lead: 68, baritone: 62, bass: 44 },
        voicingDescription: 'Symmetrical diminished tension resolving home',
      },
    ],
  },

  // 4. Big Thief / Adrianne Lenker
  {
    id: 'big_thief_dadgad',
    title: 'Vampire Empire / Shark Smile (Open Drone)',
    album: 'Dragon New Warm Mountain',
    year: 2022,
    key: 'D Modal',
    tempo: 116,
    harmonyStyle: 'pet_sounds',
    description: 'Adrianne Lenker\'s signature DADGAD fingerpicked acoustic drone. Two strings remain open throughout the entire progression, creating fragile dissonance against shifting root chords.',
    funFact: 'Adrianne almost exclusively uses DADGAD and custom altered tunings, allowing her left hand to dance along the fretboard while open unisons ring continuously.',
    artistDna: 'big_thief',
    tuningName: 'DADGAD (D A D G A D)',
    grooveVibe: 'Intimate fingerstyle, open string unisons, raw vocal crack, fragile dynamics',
    chords: [
      {
        id: 'bt_1',
        name: 'D(add9) Drone',
        numeral: 'I(add9)',
        root: 'D',
        quality: 'Modal Drone',
        inversion: 'Root',
        durationBeats: 4,
        lyricsSnippet: 'You turn me inside out and then you want the outside in...',
        vowel: 'aah',
        notes: { falsetto: 74, tenor1: 69, lead: 62, baritone: 57, bass: 38 },
        voicingDescription: 'Open DADGAD ringing E & A drone against low D bass',
      },
      {
        id: 'bt_2',
        name: 'G6/D',
        numeral: 'IV6 (Pedal)',
        root: 'G',
        quality: 'Major 6th',
        inversion: 'Slash chord',
        durationBeats: 4,
        lyricsSnippet: 'I wanted to be your woman, I wanted to be your friend...',
        vowel: 'aah',
        notes: { falsetto: 74, tenor1: 71, lead: 67, baritone: 57, bass: 38 },
        voicingDescription: 'Shifting to 4th degree while maintaining the hypnotic low D drone',
      },
      {
        id: 'bt_3',
        name: 'Bm7(11)',
        numeral: 'vi7(11)',
        root: 'B',
        quality: 'Minor 11th',
        inversion: 'Root',
        durationBeats: 4,
        lyricsSnippet: 'Holding onto the wheel with white knuckles...',
        vowel: 'ooh',
        notes: { falsetto: 74, tenor1: 69, lead: 66, baritone: 62, bass: 47 },
        voicingDescription: 'Poignant minor lift with open top D string ring',
      },
      {
        id: 'bt_4',
        name: 'Asus4',
        numeral: 'Vsus4',
        root: 'A',
        quality: 'Suspended 4th',
        inversion: 'Root',
        durationBeats: 4,
        lyricsSnippet: 'Fish swimming in the deep cold river...',
        vowel: 'aah',
        notes: { falsetto: 74, tenor1: 69, lead: 64, baritone: 57, bass: 45 },
        voicingDescription: 'Celtic suspended dominant cadence resolving back to D',
      },
    ],
  },

  // 5. D'Angelo / J Dilla
  {
    id: 'dangelo_voodoo',
    title: 'Spanish Joint / Voodoo Groove (Neo-Soul m11)',
    album: 'Voodoo',
    year: 2000,
    key: 'D Minor',
    tempo: 84,
    harmonyStyle: 'four_freshmen',
    description: 'Questlove and D\'Angelo\'s legendary behind-the-beat pocket swing (J Dilla lag). Rich minor 11th chords and half-step chromatic side-slips (Ebm11 to Dm11).',
    funFact: 'Pino Palladino played his flatwound Fender Precision bass intentionally up to 35 milliseconds behind the kick drum to create the intoxicating "slump" feel.',
    artistDna: 'dangelo',
    tuningName: 'Standard (E A D G B E)',
    grooveVibe: 'J Dilla swung backbeat lag (+35ms on 2 & 4), Fender Rhodes warmth, m11 stacks',
    chords: [
      {
        id: 'da_1',
        name: 'Dm11',
        numeral: 'i11',
        root: 'D',
        quality: 'Minor 11th',
        inversion: 'Root',
        durationBeats: 4,
        lyricsSnippet: 'Groove slipping behind the beat...',
        vowel: 'ooh',
        notes: { falsetto: 72, tenor1: 67, lead: 65, baritone: 60, bass: 38 },
        voicingDescription: 'Lush Neo-soul 5-voice cluster with G (11th) and C (b7)',
      },
      {
        id: 'da_2',
        name: 'Ebm11 (Side-slip)',
        numeral: 'biim11',
        root: 'Eb',
        quality: 'Minor 11th',
        inversion: 'Root',
        durationBeats: 2,
        lyricsSnippet: 'Chromatic slip...',
        vowel: 'doo',
        notes: { falsetto: 73, tenor1: 68, lead: 66, baritone: 61, bass: 39 },
        voicingDescription: 'Half-step chromatic passing chord tension',
      },
      {
        id: 'da_3',
        name: 'Dm11',
        numeral: 'i11',
        root: 'D',
        quality: 'Minor 11th',
        inversion: 'Root',
        durationBeats: 2,
        lyricsSnippet: 'Resolving home...',
        vowel: 'ooh',
        notes: { falsetto: 72, tenor1: 67, lead: 65, baritone: 60, bass: 38 },
        voicingDescription: 'Drop back into the pocket',
      },
      {
        id: 'da_4',
        name: 'Bbmaj9#11',
        numeral: 'bVImaj9#11',
        root: 'Bb',
        quality: 'Major 9 #11',
        inversion: 'Root',
        durationBeats: 4,
        lyricsSnippet: 'Soul warmth floating through the tape...',
        vowel: 'aah',
        notes: { falsetto: 74, tenor1: 69, lead: 65, baritone: 58, bass: 46 },
        voicingDescription: 'Spiritual Lydian color chord with deep electric bass sub',
      },
      {
        id: 'da_5',
        name: 'A7(#9b13)',
        numeral: 'V7alt',
        root: 'A',
        quality: 'Altered Dominant',
        inversion: 'Root',
        durationBeats: 4,
        lyricsSnippet: 'Turnaround to the top...',
        vowel: 'doo',
        notes: { falsetto: 73, tenor1: 69, lead: 65, baritone: 61, bass: 45 },
        voicingDescription: 'Jimi Hendrix chord / Altered dominant leading back to Dm',
      },
    ],
  },

  // 6. The Microphones / Mount Eerie
  {
    id: 'microphones_glow',
    title: 'The Glow Pt. 2 (Saturated Acoustic Fuzz)',
    album: 'The Glow Pt. 2',
    year: 2001,
    key: 'C Major',
    tempo: 92,
    harmonyStyle: 'surfer_girl',
    description: 'Phil Elverum\'s raw tape acoustic explosion: gentle intimate nylon-string strumming suddenly overtaken by heavily driven condenser mics and massive analog saturation.',
    funFact: 'Recorded on a 16-track 1-inch tape deck at Dub Narcotic Studio in Olympia, Washington with the preamp gains completely maxed out into red tape distortion.',
    artistDna: 'microphones',
    tuningName: 'Standard (E A D G B E)',
    grooveVibe: 'Lo-fi analog fuzz, downbeat acoustic rakes, intense room reverb, raw intimacy',
    chords: [
      {
        id: 'mic_1',
        name: 'Cmaj7',
        numeral: 'Imaj7',
        root: 'C',
        quality: 'Major 7th',
        inversion: 'Root',
        durationBeats: 4,
        lyricsSnippet: 'I took my shirt off in the yard...',
        vowel: 'aah',
        notes: { falsetto: 71, tenor1: 67, lead: 64, baritone: 60, bass: 48 },
        voicingDescription: 'Open ringing acoustic Cmaj7 with B on top',
      },
      {
        id: 'mic_2',
        name: 'Fmaj7',
        numeral: 'IVmaj7',
        root: 'F',
        quality: 'Major 7th',
        inversion: 'Root',
        durationBeats: 4,
        lyricsSnippet: 'No one saw me, no one cared...',
        vowel: 'ooh',
        notes: { falsetto: 72, tenor1: 69, lead: 64, baritone: 60, bass: 41 },
        voicingDescription: 'Lush open Fmaj7 with ringing high E',
      },
      {
        id: 'mic_3',
        name: 'Am (Acoustic Fuzz Blast)',
        numeral: 'vi',
        root: 'A',
        quality: 'Minor',
        inversion: 'Root',
        durationBeats: 4,
        lyricsSnippet: 'I felt the glow in my chest! [Massive tape slam]',
        vowel: 'wah',
        notes: { falsetto: 69, tenor1: 64, lead: 60, baritone: 57, bass: 45 },
        voicingDescription: 'Hard acoustic strum maxing out tape preamps',
      },
      {
        id: 'mic_4',
        name: 'G6',
        numeral: 'V6',
        root: 'G',
        quality: 'Major 6th',
        inversion: 'Root',
        durationBeats: 4,
        lyricsSnippet: 'Ringing out through the pines...',
        vowel: 'aah',
        notes: { falsetto: 71, tenor1: 67, lead: 64, baritone: 59, bass: 43 },
        voicingDescription: 'Open folk G with chime',
      },
    ],
  },

  // 7. Neutral Milk Hotel
  {
    id: 'nmh_aeroplane',
    title: 'In the Aeroplane Over the Sea (Cowboy Strum & Saw)',
    album: 'In the Aeroplane Over the Sea',
    year: 1998,
    key: 'G Major',
    tempo: 100,
    harmonyStyle: 'california_girls',
    description: 'Jeff Mangum\'s impassioned acoustic four-chord cowboy stride: G - Em - C - D. Features singing saw overtones, brass horn flourishes, and urgent forward momentum.',
    funFact: 'Jeff recorded his vocal and acoustic guitar simultaneously in a single live take at Pet Sounds Studio in Denver with producer Robert Schneider.',
    artistDna: 'neutral_milk_hotel',
    tuningName: 'Standard (E A D G B E)',
    grooveVibe: 'Urgent acoustic cowboy stride, singing saw overtones, passionate pushing pulse',
    chords: [
      {
        id: 'nmh_1',
        name: 'G',
        numeral: 'I',
        root: 'G',
        quality: 'Major',
        inversion: 'Root',
        durationBeats: 4,
        lyricsSnippet: 'What a beautiful face I have found in this place...',
        vowel: 'aah',
        notes: { falsetto: 71, tenor1: 67, lead: 62, baritone: 59, bass: 43 },
        voicingDescription: 'Full 6-string cowboy G with high D & G ring',
      },
      {
        id: 'nmh_2',
        name: 'Em',
        numeral: 'vi',
        root: 'E',
        quality: 'Minor',
        inversion: 'Root',
        durationBeats: 4,
        lyricsSnippet: 'That is circling all round the sun...',
        vowel: 'aah',
        notes: { falsetto: 71, tenor1: 67, lead: 64, baritone: 59, bass: 40 },
        voicingDescription: 'Resonant open Em with heavy downstroke',
      },
      {
        id: 'nmh_3',
        name: 'C',
        numeral: 'IV',
        root: 'C',
        quality: 'Major',
        inversion: 'Root',
        durationBeats: 4,
        lyricsSnippet: 'What a beautiful dream that could flash on the screen...',
        vowel: 'aah',
        notes: { falsetto: 72, tenor1: 67, lead: 64, baritone: 60, bass: 48 },
        voicingDescription: 'Folk C major with open top E chime',
      },
      {
        id: 'nmh_4',
        name: 'D',
        numeral: 'V',
        root: 'D',
        quality: 'Major',
        inversion: 'Root',
        durationBeats: 4,
        lyricsSnippet: 'In a blink of an eye and be gone from me...',
        vowel: 'aah',
        notes: { falsetto: 74, tenor1: 69, lead: 66, baritone: 62, bass: 50 },
        voicingDescription: 'Crisp open D leading straight back to G',
      },
    ],
  },

  // 8. Godspeed You! Black Emperor
  {
    id: 'godspeed_moya',
    title: 'Moya / The Dead Flag Blues (12/8 Drone Crescendo)',
    album: 'F# A# ∞',
    year: 1997,
    key: 'F# Minor',
    tempo: 62,
    harmonyStyle: 'smile_poly',
    description: 'Post-rock slow-burn epic in 12/8 time. Begins with sub-bass drone and field-recording spoken word, slowly accelerating into an avalanche of bowed guitars and apocalyptic crescendos.',
    funFact: 'Godspeed recordings at the Hotel2Tango studio in Montreal famously used 16mm film projectors running in the control room to set the hypnotic cinematic pace.',
    artistDna: 'godspeed',
    tuningName: 'Drop D (D A D G B E)',
    grooveVibe: '12/8 slow-motion pulse, bowed guitar drones, tape hiss, monumental slow crescendo',
    chords: [
      {
        id: 'gybe_1',
        name: 'F#m (12/8 Sub Drone)',
        numeral: 'i (Drone)',
        root: 'F#',
        quality: 'Minor',
        inversion: 'Root',
        durationBeats: 6,
        lyricsSnippet: 'The car is on fire, and there\'s no driver at the wheel...',
        vowel: 'mm',
        notes: { falsetto: 69, tenor1: 66, lead: 61, baritone: 54, bass: 42 },
        voicingDescription: 'Deep sub-octave drone with cello bow harmonics',
      },
      {
        id: 'gybe_2',
        name: 'Dmaj7/F#',
        numeral: 'bVImaj7/i',
        root: 'D',
        quality: 'Major 7th',
        inversion: 'Slash chord',
        durationBeats: 6,
        lyricsSnippet: 'And the sewers are all muddied with a thousand lonely suicides...',
        vowel: 'ooh',
        notes: { falsetto: 73, tenor1: 69, lead: 66, baritone: 62, bass: 42 },
        voicingDescription: 'Cinematic shifting 6th chord with held F# bass pedal',
      },
      {
        id: 'gybe_3',
        name: 'Bm9 (Crescendo Gathering)',
        numeral: 'iv9',
        root: 'B',
        quality: 'Minor 9th',
        inversion: 'Root',
        durationBeats: 6,
        lyricsSnippet: 'And a dark wind blows...',
        vowel: 'ooh',
        notes: { falsetto: 74, tenor1: 70, lead: 66, baritone: 59, bass: 47 },
        voicingDescription: 'Glockenspiel and tremolo guitars swell into the frame',
      },
      {
        id: 'gybe_4',
        name: 'C#m/F# (Wall of Sound Release)',
        numeral: 'v/i',
        root: 'C#',
        quality: 'Minor',
        inversion: 'Slash chord',
        durationBeats: 6,
        lyricsSnippet: 'The skyline begins to crack into light...',
        vowel: 'aah',
        notes: { falsetto: 76, tenor1: 73, lead: 68, baritone: 64, bass: 42 },
        voicingDescription: 'Maximalist post-rock climax ringing into infinite reverb',
      },
    ],
  },
];
